name: Index Apps

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - scripts/index-apps.ts

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: cd scripts && yarn
      - run: yarn ts-node index-apps.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALGOLIA_APPID: F8ONSWSRN9
          ALGOLIA_APIKEY: ${{ secrets.ALGOLIA_APIKEY }}
