name: Index Apps

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
    paths:
      - scripts/index-apps.js

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10
      - run: yarn --cwd scripts
      - run: yarn index-apps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALGOLIA_APIKEY: ${{ secrets.ALGOLIA_APIKEY }}
